### ISSUE TITLE
Documentation: How to build the project?

### ISSUE THREAD

**Issue by muhajirdev** [mathieudutour/gatsby-digital-garden#142]
I am trying to develop this project further but I am unable to run `gatsby develop` example. got error

```
yarn run v1.22.11
$ gatsby develop
internal/modules/cjs/loader.js:1089
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:
/Users/muhammadmuhajir/dev/test/essss/gatsby-digital-garden/node_modules/remark-mdx/index.js
require() of ES modules is not supported.
require() of /Users/muhammadmuhajir/dev/test/essss/gatsby-digital-garden/node_modules/remark-mdx/index.js from
/Users/muhammadmuhajir/dev/test/essss/gatsby-digital-garden/node_modules/gatsby-recipes/dist/graphql-server/server.js is
an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js
files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from
/Users/muhammadmuhajir/dev/test/essss/gatsby-digital-garden/node_modules/remark-mdx/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/muhammadmuhajir/dev/test/essss/gatsby-digital-garden/node_modules/gatsby-recipes/dist/g
raphql-server/server.js:52:17)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'ERR_REQUIRE_ESM'
}


success open and validate gatsby-configs - 0.108s
success load plugins - 1.289s
success onPreInit - 0.031s
success initialize cache - 0.018s
success copy gatsby files - 0.095s
success onPreBootstrap - 0.026s
success createSchemaCustomization - 0.112s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.341s

 ERROR 

Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following
value: Date.'. Stacktrace was 'Error: Cannot create as TypeComposer the following value: Date.
    at SchemaComposer.createTempTC
(/Users/muhammadmuhajir/dev/test/essss/gatsby-digital-garden/node_modules/graphql-compose/lib/SchemaComposer.js:365:11)
    at SchemaComposer.addAsComposer
(/Users/muhammadmuhajir/dev/test/essss/gatsby-digital-garden/node_modules/graphql-compose/lib/SchemaComposer.js:563:27)
    at createSchemaComposer
(/Users/muhammadmuhajir/dev/test/essss/gatsby-digital-garden/node_modules/gatsby/src/schema/schema-composer.js:16:18)
    at build (/Users/muhammadmuhajir/dev/test/essss/gatsby-digital-garden/node_modules/gatsby/src/schema/index.js:104:26)
    at buildSchema
(/Users/muhammadmuhajir/dev/test/essss/gatsby-digital-garden/node_modules/gatsby/src/services/build-schema.ts:19:3)'
```

**Comment by muhajirdev** [comment]
I managed to build this, turns out I can't use yarn.
