### ISSUE TITLE
Error - Cannot read property 'parentPage' of undefined

### ISSUE THREAD

**Issue by 8bitgentleman** [mathieudutour/gatsby-digital-garden#44]
I am using `gatsby-source-roamresearch` to pull down a small roam research page. I added the login info to `gatsby-config.js` and it succeeds and pulls down the graph. Once everything is built I surf to `localhost:8000` and get the following error
```
Uncaught TypeError: Cannot read property 'parentPage' of undefined
    at mapInboundRefs (data-to-note.js:30)
    at Array.map (<anonymous>)
    at dataToNote (data-to-note.js:92)
    at getRoot (hooks.js:48)
    at useStackedPagesProvider (hooks.js:58)
    at NotesLayout (stacked-layout.js:42)
    at renderWithHooks (react-dom.development.js:14804)
    at mountIndeterminateComponent (react-dom.development.js:17483)
    at beginWork (react-dom.development.js:18597)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238)
    at invokeGuardedCallback (react-dom.development.js:293)
    at beginWork$1 (react-dom.development.js:23204)
    at performUnitOfWork (react-dom.development.js:22158)
    at workLoopSync (react-dom.development.js:22131)
    at performSyncWorkOnRoot (react-dom.development.js:21757)
    at scheduleUpdateOnFiber (react-dom.development.js:21189)
    at updateContainer (react-dom.development.js:24374)
    at react-dom.development.js:24759
    at unbatchedUpdates (react-dom.development.js:21904)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:24758)
    at render (react-dom.development.js:24841)
    at app.js:103
```
Looking at the roam pages using graphql everything seems to have come in correctly.
Am I perhaps missing some step?

**Comment by 8bitgentleman** [comment]
After re-running `gatsby develop` I get a new error

```
success open and validate gatsby-configs - 0.061s
success load plugins - 1.040s
success onPreInit - 0.045s
success initialize cache - 0.008s
success copy gatsby files - 0.095s
success onPreBootstrap - 0.021s
success createSchemaCustomization - 0.008s
info Login into Roam Research...
info Downloading Roam Research database...
success Checking for changed pages - 0.006s
success source and transform nodes - 10.513s
success building schema - 0.433s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "fields" on type "File".

If you don't expect "fields" to exist on the type "File" it is most likely a typo.
However, if you expect "fields" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "fields" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "File":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: node_modules/gatsby-theme-garden/gatsby-node.js:156:26


 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "childMdx" on type "File".

If you don't expect "childMdx" to exist on the type "File" it is most likely a typo.
However, if you expect "childMdx" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "childMdx" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "File":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: node_modules/gatsby-theme-garden/gatsby-node.js:156:26

[
  GraphQLError: Cannot query field "fields" on type "File".
      at Object.Field (/Users/mtvogel/Downloads/my-digital-garden/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)
      at Object.enter (/Users/mtvogel/Downloads/my-digital-garden/node_modules/graphql/language/visitor.js:324:29)
      at Object.enter (/Users/mtvogel/Downloads/my-digital-garden/node_modules/graphql/language/visitor.js:375:25)
      at visit (/Users/mtvogel/Downloads/my-digital-garden/node_modules/graphql/language/visitor.js:242:26)
      at validate (/Users/mtvogel/Downloads/my-digital-garden/node_modules/graphql/validation/validate.js:73:24)
      at GraphQLRunner.validate (/Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby/src/query/graphql-runner.ts:98:22)
      at GraphQLRunner.query (/Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby/src/query/graphql-runner.ts:162:25)
      at /Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby/src/bootstrap/create-graphql-runner.ts:59:8
      at Object.exports.createPages (/Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby-theme-garden/gatsby-node.js:156:26)
      at runAPI (/Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby/src/utils/api-runner-node.js:330:22)
      at Promise.catch.decorateEvent.pluginName (/Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby/src/utils/api-runner-node.js:440:17)
      at Promise._execute (/Users/mtvogel/Downloads/my-digital-garden/node_modules/bluebird/js/release/debuggability.js:384:9)
      at Promise._resolveFromExecutor (/Users/mtvogel/Downloads/my-digital-garden/node_modules/bluebird/js/release/promise.js:518:18)
      at new Promise (/Users/mtvogel/Downloads/my-digital-garden/node_modules/bluebird/js/release/promise.js:103:10)
      at /Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby/src/utils/api-runner-node.js:439:14
      at tryCatcher (/Users/mtvogel/Downloads/my-digital-garden/node_modules/bluebird/js/release/util.js:16:23) {
    locations: [ [Object] ]
  },
  GraphQLError: Cannot query field "childMdx" on type "File". Did you mean "children"?
      at Object.Field (/Users/mtvogel/Downloads/my-digital-garden/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)
      at Object.enter (/Users/mtvogel/Downloads/my-digital-garden/node_modules/graphql/language/visitor.js:324:29)
      at Object.enter (/Users/mtvogel/Downloads/my-digital-garden/node_modules/graphql/language/visitor.js:375:25)
      at visit (/Users/mtvogel/Downloads/my-digital-garden/node_modules/graphql/language/visitor.js:242:26)
      at validate (/Users/mtvogel/Downloads/my-digital-garden/node_modules/graphql/validation/validate.js:73:24)
      at GraphQLRunner.validate (/Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby/src/query/graphql-runner.ts:98:22)
      at GraphQLRunner.query (/Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby/src/query/graphql-runner.ts:162:25)
      at /Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby/src/bootstrap/create-graphql-runner.ts:59:8
      at Object.exports.createPages (/Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby-theme-garden/gatsby-node.js:156:26)
      at runAPI (/Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby/src/utils/api-runner-node.js:330:22)
      at Promise.catch.decorateEvent.pluginName (/Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby/src/utils/api-runner-node.js:440:17)
      at Promise._execute (/Users/mtvogel/Downloads/my-digital-garden/node_modules/bluebird/js/release/debuggability.js:384:9)
      at Promise._resolveFromExecutor (/Users/mtvogel/Downloads/my-digital-garden/node_modules/bluebird/js/release/promise.js:518:18)
      at new Promise (/Users/mtvogel/Downloads/my-digital-garden/node_modules/bluebird/js/release/promise.js:103:10)
      at /Users/mtvogel/Downloads/my-digital-garden/node_modules/gatsby/src/utils/api-runner-node.js:439:14
      at tryCatcher (/Users/mtvogel/Downloads/my-digital-garden/node_modules/bluebird/js/release/util.js:16:23) {
    locations: [ [Object] ]
  }
]

 ERROR #11321  PLUGIN

"gatsby-theme-garden" threw an error while running the createPages lifecycle:

Could not query notes

  181 |     if (result.errors) {
  182 |       console.log(result.errors);
> 183 |       throw new Error(`Could not query notes`, result.errors);
      |             ^
  184 |     }
  185 | 
  186 |     await copyFile(

File: node_modules/gatsby-theme-garden/gatsby-node.js:183:13



  Error: Could not query notes
  
  - gatsby-node.js:183 Object.exports.createPages
    [my-digital-garden]/[gatsby-theme-garden]/gatsby-node.js:183:13
  
  - api-runner-node.js:330 runAPI
    [my-digital-garden]/[gatsby]/src/utils/api-runner-node.js:330:16
  
  - From previous event:
  
  - api-runner-node.js:440 Promise.catch.decorateEvent.pluginName
    [my-digital-garden]/[gatsby]/src/utils/api-runner-node.js:440:9
  
  - From previous event:
  
  - api-runner-node.js:439 
    [my-digital-garden]/[gatsby]/src/utils/api-runner-node.js:439:14
  
  - timers.js:456 processImmediate
    internal/timers.js:456:21
  
  - From previous event:
  
  - api-runner-node.js:431 
    [my-digital-garden]/[gatsby]/src/utils/api-runner-node.js:431:13
  
  - From previous event:
  
  - api-runner-node.js:347 module.exports
    [my-digital-garden]/[gatsby]/src/utils/api-runner-node.js:347:3
  
  - create-pages.ts:25 createPages
    [my-digital-garden]/[gatsby]/src/services/create-pages.ts:25:9
  
  - interpreter.js:707 Interpreter.exec
    [my-digital-garden]/[xstate]/lib/interpreter.js:707:27
  
  - interpreter.js:210 Interpreter.execute
    [my-digital-garden]/[xstate]/lib/interpreter.js:210:22
  
  - interpreter.js:230 Interpreter.update
    [my-digital-garden]/[xstate]/lib/interpreter.js:230:18
  
  - interpreter.js:131 
    [my-digital-garden]/[xstate]/lib/interpreter.js:131:23
  
  - scheduler.js:60 Scheduler.process
    [my-digital-garden]/[xstate]/lib/scheduler.js:60:13
  
  - scheduler.js:44 Scheduler.schedule
    [my-digital-garden]/[xstate]/lib/scheduler.js:44:14
  
  - interpreter.js:127 Interpreter.send
    [my-digital-garden]/[xstate]/lib/interpreter.js:127:29
  
  - interpreter.js:825 actor.id
    [my-digital-garden]/[xstate]/lib/interpreter.js:825:23
  

failed createPages - 0.150s
```

**Comment by 8bitgentleman** [comment]
Ok I think I found the error with this. After pulling pages from Roam any blocks that contain `{{ }}` cause everything to fail. This means that any of the special functions that roam has (like queries or embeds) cause this to fail
