### ISSUE TITLE
Build error while using gatsby-transformer-markdown-references

### ISSUE THREAD

**Issue by kamilkollmanvd** [mathieudutour/gatsby-digital-garden#79]
I am experiencing a build error while using the markdown-references plugin; it throws an error on the build, but interestingly the process doesn't stop then - instead, it is frozen and the spinner is rotating endlessly. Removing the plugin from gatsby-config fixes the build issue (but obviously that's not the point).

Error:
```
Missing onError handler for invocation 'building-schema', error was 'Error: Cannot resolve types for ReferenceTarget'. Stacktrace was 'Error: Cannot
resolve types for ReferenceTarget
    at resolveTypeArrayAsThunk (/Users/kamil/dev/venturedevs/knowledge/node_modules/graphql-compose/lib/utils/configAsThunk.js:93:11)
    at GraphQLUnionType.gqType._types (/Users/kamil/dev/venturedevs/knowledge/node_modules/graphql-compose/lib/UnionTypeComposer.js:125:61)
    at GraphQLUnionType.getTypes (/Users/kamil/dev/venturedevs/knowledge/node_modules/graphql/type/definition.js:806:26)
    at typeMapReducer (/Users/kamil/dev/venturedevs/knowledge/node_modules/graphql/type/schema.js:272:28)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/Users/kamil/dev/venturedevs/knowledge/node_modules/graphql/type/schema.js:145:28)
    at SchemaComposer.buildSchema (/Users/kamil/dev/venturedevs/knowledge/node_modules/graphql-compose/lib/SchemaComposer.js:130:12)
    at addCustomResolveFunctions (/Users/kamil/dev/venturedevs/knowledge/node_modules/gatsby/src/schema/schema.js:754:45)
    at updateSchemaComposer (/Users/kamil/dev/venturedevs/knowledge/node_modules/gatsby/src/schema/schema.js:187:9)
    at buildSchema (/Users/kamil/dev/venturedevs/knowledge/node_modules/gatsby/src/schema/schema.js:62:3)
    at build (/Users/kamil/dev/venturedevs/knowledge/node_modules/gatsby/src/schema/index.js:105:18)
    at buildSchema (/Users/kamil/dev/venturedevs/knowledge/node_modules/gatsby/src/services/build-schema.ts:19:3)'
```

gatsby-config.js:
```
module.exports = (opts) => {
  const { contentPath, imagesPath } = { ...defaultOptions, ...opts };

  return {
    plugins: [
      "gatsby-plugin-sass",
      "gatsby-plugin-sharp",
      "gatsby-plugin-react-helmet",
      "gatsby-transformer-sharp",
      {
        resolve: "gatsby-source-filesystem",
        options: {
          name: "images",
          path: imagesPath,
        },
        __key: "images",
      },
      {
        resolve: "gatsby-plugin-mdx",
        options: {
          extensions: [`.mdx`, `.md`],
          defaultLayouts: {
            default: require.resolve(
              "./src/components/PostLayout/PostLayout.jsx"
            ),
          },
          gatsbyRemarkPlugins: [
            {
              resolve: `gatsby-remark-double-brackets-link`,
              options: {
                stripBrackets: true,
              },
            },
          ],
        },
      },
      {
        resolve: `gatsby-transformer-markdown-references`,
        options: {
          types: ["mdx"],
        },
      },
      {
        resolve: "gatsby-source-filesystem",
        options: {
          name: "posts",
          path: contentPath,
        },
        __key: "posts",
      },
      {
        resolve: "gatsby-plugin-page-creator",
        options: {
          path: contentPath,
        },
      },
    ],
  };
};
```

**Comment by kamilkollmanvd** [comment]
Issue seems to be present only when type "MarkdownRemark" provided in the options for plugin. "Mdx" works just fine.
