### ISSUE TITLE
Could not download the Roam Research data

### ISSUE THREAD

**Issue by dofine** [mathieudutour/gatsby-digital-garden#84]
Hi, couldn't get it to work with roamresearch. Any help is appreciated.

```
No node found for selector: input[name="email"]
```

```
Error: Protocol error (Runtime.evaluate): Session closed. Most likely the page has been closed.
    at CDPSession.send
(/Users/dofine/Documents/GitHub/my-digital-garden/node_modules/puppeteer/lib/Connection.js:141:35)
    at ExecutionContext._evaluateInternal
(/Users/dofine/Documents/GitHub/my-digital-garden/node_modules/puppeteer/lib/ExecutionContext.js:47:18)
    at ExecutionContext.evaluateHandle
(/Users/dofine/Documents/GitHub/my-digital-garden/node_modules/puppeteer/lib/ExecutionContext.js:36:21)
    at ExecutionContext.<anonymous>
(/Users/dofine/Documents/GitHub/my-digital-garden/node_modules/puppeteer/lib/helper.js:95:27)
    at /Users/dofine/Documents/GitHub/my-digital-garden/node_modules/puppeteer/lib/DOMWorld.js:104:44
  -- ASYNC --
    at Frame.<anonymous>
(/Users/dofine/Documents/GitHub/my-digital-garden/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.type
(/Users/dofine/Documents/GitHub/my-digital-garden/node_modules/puppeteer/lib/Page.js:793:33)
    at checkLogin
(/Users/dofine/Documents/GitHub/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:61:20)
    at checkLogin
(/Users/dofine/Documents/GitHub/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:70:9)
    at checkLogin
(/Users/dofine/Documents/GitHub/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:70:9)
    at Object.downloadRoam [as default]
(/Users/dofine/Documents/GitHub/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:101:9)
    at Object.exports.sourceNodes (/Users/dofine/Documents/GitHub/my-digital-garden/node_modules/gatsby-
source-roamresearch/lib/source-nodes.js:12:19)
    at runAPI (/Users/dofine/Documents/GitHub/my-digital-garden/node_modules/gatsby/src/utils/api-runner
-node.js:485:16)


 ERROR

Could not download the Roam Research data
```

**Comment by Stvad** [comment]
I had trouble with download module as-well. I ended up mostly transitioning for loading the JSON from file for https://roam.garden (and using things like https://github.com/MatthieuBizien/roam-to-git/ for actual download)

A minimal change to accomplish that would be to change the following https://github.com/mathieudutour/gatsby-digital-garden/blob/master/packages/gatsby-source-roamresearch/src/source-nodes.ts#L18 to read from the file you want vs using the fetch module

**Comment by mathieudutour** [comment]
yeah I mean the point is to not have to download the file manually. Maybe the markup of Roam changed?

**Comment by Stvad** [comment]
yeah, I understand, suggesting options 😉. 

generally I've seen the dedicated backup tools having trouble being consistently able to do the backup 🙁 (roam changes/etc) 

- https://github.com/MatthieuBizien/roam-to-git/ is fairly stable after latest updates
- https://github.com/everruler12/roam2github haven't used personally but heard good things, it's also JS based - so integrating with it (and delegating keeping up to date on backup stuff to it) can be a good option

**Comment by JayFarei** [comment]
Have you considered [this approach](https://davidbieber.com/snippets/2020-12-28-publishing-blog-posts-from-roam-research-quickly-and-automatically/) instead of using backups?

**Comment by Stvad** [comment]
The theme works with full JSON export (vs partial snippets in the article). That said it should still work ( though it'd be a bit more heavy-weight) if you pair that with sourcing the JSON from local file as mentioned above & make the Github WF update the json file.

**Comment by ahmedalhulaibi** [comment]
I got similar errors. It doesn't look like roam has changed. I wonder if the page is failing to load given that the errors are not consistent

```
info Login into Roam Research...

 ERROR 

Error: No node found for selector: input[name="email"]
    at Object.assert (/home/ahmed/my-digital-garden/node_modules/puppeteer/lib/helper.js:29:15)
    at DOMWorld.type (/home/ahmed/my-digital-garden/node_modules/puppeteer/lib/DOMWorld.js:291:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at checkLogin (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:61:9)
    at checkLogin (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:70:9)
    at checkLogin (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:70:9)
    at Object.downloadRoam [as default]
(/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:101:9)
    at Object.exports.sourceNodes
(/home/ahmed/my-digital-garden/node_modules/gatsby-source-roamresearch/lib/source-nodes.js:12:19)
    at runAPI
(/home/ahmed/my-digital-garden/node_modules/gatsby/src/utils/api-runner-node.js:485:16)
  -- ASYNC --
    at Frame.<anonymous> (/home/ahmed/my-digital-garden/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.type (/home/ahmed/my-digital-garden/node_modules/puppeteer/lib/Page.js:793:33)
    at checkLogin (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:61:20)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
    at checkLogin (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:70:9)
    at checkLogin (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:70:9)
    at Object.downloadRoam [as default]
(/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:101:9)
    at Object.exports.sourceNodes
(/home/ahmed/my-digital-garden/node_modules/gatsby-source-roamresearch/lib/source-nodes.js:12:19)
    at runAPI
(/home/ahmed/my-digital-garden/node_modules/gatsby/src/utils/api-runner-node.js:485:16)


 ERROR 

Could not download the Roam Research data
```
___
```
info Login into Roam Research...

 ERROR 

Error: Login Button not found
    at checkLogin (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearc
h/lib/index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at checkLogin (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearc
h/lib/index.js:70:9)
    at Object.downloadRoam [as default] (/home/ahmed/my-digital-garden/node_mod
ules/fetch-roamresearch/lib/index.js:101:9)
    at Object.exports.sourceNodes (/home/ahmed/my-digital-garden/node_modules/g
atsby-source-roamresearch/lib/source-nodes.js:12:19)
    at runAPI (/home/ahmed/my-digital-garden/node_modules/gatsby/src/utils/api-
runner-node.js:485:16)


 ERROR 

Could not download the Roam Research data
```

**Comment by ahmedalhulaibi** [comment]
I suspect it may be a client side problem when the page is loading.

I added `await page.waitForNavigation({ waitUntil: 'networkidle0'  });` at the top of `checkLogin` and it's consistently timing out after 30s

Seems like a client side problem, not really an issue with the library itself. I set it to 16 minutes and even then it timed out.

I'm not too familiar with a js stack but I'll keep at this for a bit to see what's going on.

```
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111
    at FrameManager.waitForFrameNavigation (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/node_modules/puppeteer/lib/FrameManager.js:107:23)
    at Frame.waitForNavigation (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/node_modules/puppeteer/lib/FrameManager.js:298:16)
    at Page.waitForNavigation (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/node_modules/puppeteer/lib/Page.js:492:16)
    at checkLogin (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:49:5)
    at checkLogin (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:71:9)
    at Object.downloadRoam [as default] (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:102:9)
    at Object.exports.sourceNodes (/home/ahmed/my-digital-garden/node_modules/gatsby-source-roamresearch/lib/source-nodes.js:12:19)
    at runAPI (/home/ahmed/my-digital-garden/node_modules/gatsby/src/utils/api-runner-node.js:485:16)
  -- ASYNC --
    at Frame.<anonymous> (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.waitForNavigation (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/node_modules/puppeteer/lib/Page.js:492:53)
    at Page.<anonymous> (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/node_modules/puppeteer/lib/helper.js:95:27)
    at checkLogin (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:49:16)
    at checkLogin (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:71:15)
    at Object.downloadRoam [as default] (/home/ahmed/my-digital-garden/node_modules/fetch-roamresearch/lib/index.js:102:9)
    at Object.exports.sourceNodes (/home/ahmed/my-digital-garden/node_modules/gatsby-source-roamresearch/lib/source-nodes.js:12:19)
    at runAPI (/home/ahmed/my-digital-garden/node_modules/gatsby/src/utils/api-runner-node.js:485:16)


 ERROR 

Could not download the Roam Research data
```

**Comment by mathieudutour** [comment]
you could try with `networkidle2` instead of `networkidle0` (that one might be a bit too restrictive for web app that continuously fetch stuff)

**Comment by ahmedalhulaibi** [comment]
Thanks for the tip @mathieudutour in the end it wasn't networking. I found a couple of problems.

- The topbar CSS class name has changed. I opened #127 to address this
- Sign in race - I disabled headless and noticed that on the sign in page, the script seems to enter my email more than once. This was intermittent. I suspect it is a race condition related to the login state flow. I'm not so sure about how to fix this one but I'll give it a shot

**Comment by mathieudutour** [comment]
Ah good catch for the class name. That's the issue with an approach like that while there is no API to get the content - we rely on the frontend of Roam not changing too much.

Regarding the race condition in the sign in: it's all in this function https://github.com/mathieudutour/gatsby-digital-garden/blob/master/packages/fetch-roamresearch/src/index.ts#L35-L71. You can see that we see if we are logged in, we wait a bit before trying to sign-in again but I realise that we aren't clearing the input before typing it again.

**Comment by mathieudutour** [comment]
I think the latest version is a lot more reliable so I'm going to close this. Thanks @ahmedalhulaibi !
